version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

    ports:
      - "5435:5432"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://test_user:test_password@db:5432/mydatabase
